python-django-assessment/config/urls.py
# -*- coding: utf-8 -*-
from django.conf import settings
from django.urls import include, path
from django.conf.urls.static import static
from django.contrib import admin
from django.views import defaults as default_views
from django.views.generic import TemplateView

app_name = 'movies'
urlpatterns = [
    path('', TemplateView.as_view(template_name='pages/home.html'), name='home'),
    path('movies/', include('moviesapp.movies.urls', namespace='movie')),
    path('ratings/', include('star_ratings.urls', namespace='ratings')),

    path(settings.ADMIN_URL, admin.site.urls),  # {% url 'admin:index' %}
] + static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

if settings.DEBUG:
    # This allows the error pages to be debugged during development, just visit
    # these url in browser to see how these error pages look like.
    urlpatterns += [
        path('400/', default_views.bad_request, kwargs={'exception': Exception('Bad Request!')}),
        path('403/', default_views.permission_denied, kwargs={'exception': Exception('Permission Denied')}),
        path('404/', default_views.page_not_found, kwargs={'exception': Exception('Page not Found')}),
        path('500/', default_views.server_error),
    ]

python-django-assessment/moviesapp/movies/urls.py
# -*- coding: utf-8 -*-
from django.urls import path

from . import views


app_name = 'movies'
urlpatterns = [
    path('', view=views.MovieListView.as_view(), name='index'),
    path('<int:pk>/',view=views.MovieDetailView.as_view(), name='detail'),
    path('create/', view=views.MovieCreateView.as_view(), name='create'),
    path('update/<int:pk>/',view=views.MovieUpdateView.as_view(), name='update'),
    path('delete/<int:pk>/',view=views.MovieDeleteView.as_view(), name='delete'),
    path('results/', views.SearchView.as_view(), name='search'),
]

python-django-assessment/moviesapp/movies/models.py
# -*- coding: utf-8 -*-
from django.urls import reverse
from django.core.validators import RegexValidator
from django.db import models
from django.utils.translation import ugettext_lazy as _
from star_ratings.models import Rating
from django.contrib.contenttypes.fields import GenericRelation

class Movie(models.Model):
    title = models.CharField(_('Movie\'s title'), max_length=255,unique=True)
    year = models.PositiveIntegerField(default=2019)
    # Example: PG-13
    rated = models.CharField(max_length=64,default='PG-13')
    released_on = models.DateField(_('Release Date'))
    genre = models.CharField(max_length=255)
    director = models.CharField(max_length=255)
    plot = models.TextField(blank=True, null=True)
    created_at = models.DateTimeField(auto_now_add=True, editable=False)
    updated_at = models.DateTimeField(auto_now=True, editable=False)
    photo = models.ImageField(upload_to='img',default='img/default-cover.jpg')
    # Todo: add Rating models
    rating= GenericRelation(Rating)


    class Meta:
       ordering = ['-rating__average','created_at']


    def __str__(self):
        return self.title

    def get_absolute_url(self):
        return reverse('movies:detail', kwargs={'pk': self.pk})

python-django-assessment/moviesapp/movies/views.py
# -*- coding: utf-8 -*-

"""Movies views."""

from django.views.generic import ListView, DetailView, CreateView, UpdateView, DeleteView
from django.contrib import messages
from django.shortcuts import redirect
from django.http import Http404
from django.urls import reverse_lazy
from django.contrib.messages.views import SuccessMessageMixin
from .models import Movie


class MovieListView(ListView):
    """Show all movies."""
    model = Movie

class MovieDetailView(DetailView):
    """Show the requested movie."""
    model = Movie


class SearchView(ListView):
    model = Movie
    template_name = 'movies/movie_list.html'
    context_object_name = 'all_results'

    def get_queryset(self):
        result = super(SearchView, self).get_queryset()
        query = self.request.GET.get('search')
        if query:
            result = Movie.objects.filter(title__contains=query)
        else:
            result = Movie.objects.all()
        return result

class MovieCreateView(SuccessMessageMixin,CreateView):
    """Create a new movie."""
    model = Movie
    fields = ['title', 'year', 'rated', 'released_on', 'genre', 'director', 'plot','photo']
    success_message = 'The movie created successfully'


class MovieUpdateView(SuccessMessageMixin,UpdateView):
    """Update the requested movie."""
    model = Movie
    fields = ['title','director','released_on']
    success_message = '%(director)s The movie updated successfully'
    error_message='The update has failed'



class MovieDeleteView(SuccessMessageMixin,DeleteView):
    """Delete the requested movie."""
    success_url = reverse_lazy('movies:index')
    success_message = 'The movie deleted successfully'
    model = Movie

python-django-assessment/moviesapp/templates/403_csrf.html
{% extends 'base.html' %}

{% block title %}Forbidden (403){% endblock %}

{% block content %}
<h1>Forbidden (403)</h1>

<p>CSRF verification failed. Request aborted.</p>
{% endblock content %}

python-django-assessment/moviesapp/templates/base.html
{% load static i18n %}

<!DOCTYPE html>
<html lang="en">

  <head>

    <meta charset="utf-8">
    <meta http-equiv="x-ua-compatible" content="ie=edge">
    <title>{% block title %}{% trans 'MoviesCRUDApp' %}{% endblock %}</title>
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <meta name="description" content="">
    <meta name="author" content="">
    <link rel="icon" href="{% static 'img/favicon.ico' %}">

    {% block css %}
      <link href="{% static 'css/style.css' %}" rel="stylesheet">
      <link href="{% static 'css/bootstrap-theme.min.css' %}" rel="stylesheet">
      <link href="{% static 'css/bootstrap.min.css' %}" rel="stylesheet">
    {% endblock %}

    {% block javascript %}
      <script src="{% static 'js/bootstrap.min.js' %}"></script>
      <script src="{% static 'js/jquery.min.js' %}"></script>
      <!-- HTML5 shim, for IE6-8 support of HTML5 elements -->
      <!--[if lt IE 9]>
        <script src="js/respond.min.js"></script>
        <script src="js/html5shiv.min.js"></script>
      <![endif]-->
    {% endblock %}

  </head>

  <body>

    <nav class="navbar navbar-inverse navbar-fixed-top" role="navigation">
      <div class="container">
        <div class="navbar-header">
          <button type="button" class="navbar-toggle" data-toggle="collapse" data-target=".navbar-collapse">
            <span class="icon-bar"></span>
            <span class="icon-bar"></span>
            <span class="icon-bar"></span>
          </button>
          <a class="navbar-brand" href="{% url 'home' %}"><img src="{% static 'img/django-logo.png' %}" width="80" alt="Django Framework"/></a>
        </div>
        <div class="collapse navbar-collapse">
          <ul class="nav navbar-nav">
            <li class="active"><a href="{% url 'home' %}">{% trans 'Home' %}</a></li>
            <li class="active"><a href="{% url 'movies:index' %}">{% trans 'Movies' %}</a></li>
          </ul>
        </div><!--/.nav-collapse -->
      </div>
    </nav>
    <div class="container">

      {% if messages %}
        <div class="messages">
          {% for message in messages %}
            <p class="msg msg-{{ message.tags }}">{{ message }}</p>
          {% endfor %}
        </div>
      {% endif %}

      {% block content %}{% endblock %}

        <hr>
        <footer>
            <p>&copy; 2005 - {% now 'Y' %} {% blocktrans %}Django Software Foundation and individual contributors. Django is a registered trademark of the Django Software Foundation.{% endblocktrans %}</p>
        </footer>

    </div> <!-- /container -->

    {% block modal %}{% endblock %}

    {% block scripts %}{% endblock %}

  </body>
</html>


{% comment %}
  <body>

    <div class="m-b-1">
      <nav class="navbar navbar-dark navbar-static-top bg-inverse">
        <div class="container">
          <a class="navbar-brand" href="/">MoviesCRUDApp</a>
          <button type="button" class="navbar-toggler hidden-sm-up pull-xs-right" data-toggle="collapse" data-target="#bs-navbar-collapse-1">
            &#9776;
          </button>

          <!-- Collect the nav links, forms, and other content for toggling -->
          <div class="collapse navbar-toggleable-xs" id="bs-navbar-collapse-1">
            <ul class="nav navbar-nav">
              <li class="nav-item">
                <a class="nav-link" href="{% url 'home' %}">Home</a>
              </li>
              <li class="nav-item">
                <a class="nav-link" href="{% url 'about' %}">About</a>
              </li>
            </ul>

            <ul class="nav navbar-nav pull-xs-right">
              {% if request.user.is_authenticated %}
                <li class="nav-item">
                  <a class="nav-link" href="{% url 'movies:detail' request.user.username  %}">{% trans "My Profile" %}</a>
                </li>
                <li class="nav-item">
                  <a class="nav-link" href="{% url 'account_logout' %}">{% trans "Sign Out" %}</a>
                </li>
              {% else %}
                <li class="nav-item">
                  <a id="sign-up-link" class="nav-link" href="{% url 'account_signup' %}">{% trans "Sign Up" %}</a>
                </li>
                <li class="nav-item">
                  <a id="log-in-link" class="nav-link" href="{% url 'account_login' %}">{% trans "Sign In" %}</a>
                </li>
              {% endif %}
            </ul>
          </div>
        </div>
      </nav>
    </div>

    <div class="container">

      {% if messages %}
          {% for message in messages %}
              <div class="alert {% if message.tags %}alert-{{ message.tags }}{% endif %}">{{ message }}</div>
          {% endfor %}
      {% endif %}

      {% block content %}
        <p>Use this document as a way to quick start any new project.</p>
      {% endblock content %}

    </div> <!-- /container -->

    {% block modal %}{% endblock modal %}

    <!-- Le javascript
    ================================================== -->
    <!-- Placed at the end of the document so the pages load faster -->
    {% block javascript %}
      <!-- Required by Bootstrap v4 Alpha 4 -->
      <script src="https://ajax.googleapis.com/ajax/libs/jquery/3.1.1/jquery.min.js" integrity="sha384-3ceskX3iaEnIogmQchP8opvBy3Mi7Ce34nWjpBIwVTHfGYWQS9jwHDVRnpKKHJg7" crossorigin="anonymous"></script>
      <script src="https://cdnjs.cloudflare.com/ajax/libs/tether/1.3.7/js/tether.min.js" integrity="sha384-XTs3FgkjiBgo8qjEjBk0tGmf3wPrWtA6coPfQDfFEY8AnYJwjalXCiosYRBIBZX8" crossorigin="anonymous"></script>
      <script src="https://maxcdn.bootstrapcdn.com/bootstrap/4.0.0-alpha.4/js/bootstrap.min.js" integrity="sha384-VjEeINv9OSwtWFLAtmc4JCtEJXXBub00gtSnszmspDLCtC0I4z4nqz7rEFbIZLLU" crossorigin="anonymous"></script>

      <!-- Your stuff: Third-party javascript libraries go here -->

      <!-- place project specific Javascript in this file -->
      {% compress js %}
      <script src="{% static 'js/project.js' %}"></script>
      {% endcompress %}

    {% endblock javascript %}
  </body>
</html>
{% endcomment %}

python-django-assessment/moviesapp/templates/movies/movie_confirm_delete.html
{% extends 'base.html' %} {% load static i18n %} {% block title %}{% trans
'Movie' %}: {% trans 'Delete' %}{% endblock %} {% block content %}

<h1>{{ object.title }}</h1>

<form
  class="form-horizontal"
  method="post"
  action="{% url 'movies:delete' object.pk %}"
>
  {% csrf_token %}
  {{ form.as_p }}
  <p>{% trans 'Are you sure you want to delete the movie?' %}</p>
  <div class="control-group">
    <div class="controls">
      <button type="submit" class="btn btn-primary">
        {% trans 'Yes, delete' %}
      </button>
    </div>
  </div>
</form>
{% endblock %}

python-django-assessment/moviesapp/templates/movies/movie_detail.html
{% extends 'base.html' %} {% load static i18n %} {% block title %}{{ object.title }} {{ object.year }} {% endblock %} {% block content %} {% load ratings %}

<link rel="stylesheet" href="{% static 'star-ratings/css/star-ratings.css' %}">
<script type="text/javascript" src="{% static 'star-ratings/js/dist/star-ratings.min.js' %}"></script>

<h3>{{ object.title }}</h3>

<div class="row">
  <div class="col-sm-12">
    <dl class="dl-horizontal">
      <!-- TODO: Implement movie details view-->
      <div>
      <div style='margin-bottom:3%'><img src='{{ MEDIA_URL }}{{object.photo}}'></div>
      <p><label>Year: {{ object.year }}</label></p>
      <p><label>Release Date: {{ object.released_on }}</label></p>
      <p><label>Rated: {{ object.rated }}</label></p>
      <p><label>Director: {{ object.director}}</label></p>
      <p><label>Genre: {{ object.genre }}</label></p>
      <p><label>Plot: {{ object.plot }}</label></p>
      {% ratings object %}
      </div>

    </dl>
  </div>
</div>
{% endblock %}

python-django-assessment/moviesapp/templates/movies/movie_form.html
{% extends 'base.html' %}
{% load static i18n %}

{% block title %}{% trans 'Movie' %}{% endblock %}

{% block content %}
<h1>{{ object.title }}</h1>


<form class="form-horizontal" method="post" 
{% if 'create' in request.path %}
  action="{% url 'movies:create' %}"
{% else %}
  action="{% url 'movies:update' object.pk %}"
{% endif %}>
  {% csrf_token %}
  {{ form.as_p }}
  <div class="control-group">
    <div class="controls">
      <button type="submit" class="btn btn-primary">
        {% if 'create' in request.path %}{% trans 'Create' %}{% else %}{% trans 'Update' %}{% endif %}
      </button>
    </div>
  </div>
</form>
{% endblock %}

python-django-assessment/moviesapp/templates/movies/movie_list.html
{% extends 'base.html' %} {% load static i18n %} {% block title %}{% trans 'Movies' %}{% endblock %} {% block content %}
<h3>{% trans 'Movies' %}</h3>
<table class="table table-striped">
  <thead>
        <form method="GET" action="{% url 'movie:search' %}" >
            <input type="search" name="search">
            <button  type="submit"> Search </button>
        </form>

        <tr>
      <!-- TODO: Add table columns -->
      <th><b>ID</b></th>
      <th><b>Title</b></th>
      <th><b>Year</b></th>
      <th><b>Rated</b></th>
      <th><b>Released</b></th>
    </tr>
  </thead>
  <tbody>
  {% if all_results|length == 0 %}
    {% for movie in movie_list %}
    <tr>
      <td>
          <a href="{{ movie.get_absolute_url }}">{{ movie.pk }}</a>
      </td>
      <td><a href="{{ movie.get_absolute_url }}">{{ movie.title }}</a></td>
      <td>{{ movie.year }}</td>
      <td>{{ movie.rated }}</td>
      <td>{{ movie.released_on }}</td>
      <!-- TODO: Render more movie properties and make sure action links work -->
      <td><a href="{% url 'movie:update' movie.pk %}">Edit</a></td>
      <td><a href="{% url 'movie:delete' movie.pk %}">Delete</a></td>
    </tr>
    {% empty %}
      <h2>No results found</h2>
    {% endfor %}

  {% else %}
    {% for movie in all_results %}
    <tr>
      <td>
        {{ movie.pk }}
      </td>
      <td><a href="{{ movie.get_absolute_url }}">{{ movie.title }}</a></td>
      <td>{{ movie.year }}</td>
      <td>{{ movie.rated }}</td>
      <td>{{ movie.released_on }}</td>
      <!-- TODO: Render more movie properties and make sure action links work -->
      <td><a href="{% url 'movie:update' movie.pk %}">Edit</a></td>
      <td><a href="{% url 'movie:delete' movie.pk %}">Delete</a></td>
    </tr>

    {% endfor %}

  {% endif %}


    <tr>
      <td colspan="6"><a href="{% url 'movie:create' %}">Add new movie</a></td>
    </tr>
  </tbody>
</table>
{% endblock content %}

python-django-assessment/moviesapp/templates/pages/home.html
{% extends 'base.html' %} {% load static i18n %}

<div class="jumbotron">
  <h1>{% blocktrans %}Welcome to Django Framework{% endblocktrans %}</h1>
  <p>
    {% blocktrans %}Congratulations! You have successfully installed the Movies
    CRUD App. You are currently running Django Framework.{% endblocktrans %}
  </p>
  <p>
    <a
      class="btn btn-success btn-lg"
      href="https://github.com/django/django"
      target="_blank"
      >{% blocktrans %}Fork Django on GitHub{% endblocktrans %} &raquo;</a
    >
  </p>
</div>

<div class="row">
  <div class="col-md-4">
    <div class="panel panel-default">
      <div class="panel-heading">
        <h3 class="panel-title">
          {% blocktrans %}Follow Development{% endblocktrans %}
        </h3>
      </div>
      <div class="panel-body">
        <p>
          {% blocktrans %}Django is under active development...{% endblocktrans %}
        </p>
      </div>
    </div>
  </div>

  <div class="col-md-4">
    <div class="panel panel-default">
      <div class="panel-heading">
        <h3 class="panel-title">
          {% blocktrans %}Discover Modules{% endblocktrans %}
        </h3>
      </div>
      <div class="panel-body">
        <p>{% blocktrans %}The community is working on...{% endblocktrans %}</p>
      </div>
    </div>
  </div>

  <div class="col-md-4">
    <div class="panel panel-default">
      <div class="panel-heading">
        <h3 class="panel-title">
          {% blocktrans %}Help &amp; Support{% endblocktrans %}
        </h3>
      </div>
      <div class="panel-body">
        <p>
          {% blocktrans %}If you need any help or support while developing with
          Django, you may reach us via...{% endblocktrans %}
        </p>
      </div>
    </div>
  </div>
</div>